# Generated by Django 4.1.7 on 2023-04-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
